spring.application.name=gateway-server

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL}/realms/${REALM_NAME}/protocol/openid-connect/certs